DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS rental;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS users;


CREATE TABLE users
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name            VARCHAR(50)  NOT NULL,
    email                VARCHAR(50)  NOT NULL UNIQUE,
    phone                VARCHAR(30)  NOT NULL UNIQUE,
    address              VARCHAR(100) NULL,
    date_of_birthday     DATE         NULL,
    passwords            VARCHAR(256) NOT NULL,
    agreement            BOOLEAN      NOT NULL,
    reset_password_token VARCHAR(256)  NULL,
    roles                VARCHAR(7)   NOT NULL,
    date_of_creation     TIMESTAMP    NOT NULL
);

CREATE TABLE car
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand            VARCHAR(20)      NOT NULL,
    model            VARCHAR(20)      NOT NULL,
    type_car         VARCHAR(20)      NOT NULL,
    image            VARCHAR(256),
    year_of_release  INT              NOT NULL CHECK (year_of_release > 2000),
    color            VARCHAR(20)      NOT NULL,
    fuel             VARCHAR(20)      NOT NULL,
    engine_capacity  DOUBLE PRECISION NOT NULL CHECK (engine_capacity > 0.0),
    horse_power      INT              NOT NULL CHECK (horse_power > 0),
    transmission     VARCHAR(20)      NOT NULL,
    fuel_consumption DOUBLE PRECISION NOT NULL CHECK (fuel_consumption > 0.0),
    quantity_places  INT              NOT NULL CHECK (quantity_places > 0),
    quantity_doors   INT              NOT NULL CHECK (quantity_doors > 0),
    trunk_volume     INT              NOT NULL CHECK (trunk_volume > 0),
    status           VARCHAR(10)      NOT NULL,
    state_check      VARCHAR(10)      NOT NULL,
    vin_code         VARCHAR(20)      NOT NULL UNIQUE,
    numbers          VARCHAR(20)      NOT NULL UNIQUE,
    price            DOUBLE PRECISION NOT NULL CHECK ( price > 0 )
);

CREATE TABLE documents
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INT         NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    passport_No       VARCHAR(9)  NOT NULL UNIQUE,
    driver_license_No VARCHAR(9)  NOT NULL UNIQUE,
    status_check      VARCHAR(15) NOT NULL
);

CREATE TABLE rental
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id           INT              NOT NULL REFERENCES car (id) ON DELETE CASCADE,
    user_id          INT              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rental_date      DATE             NOT NULL,
    return_date      DATE             NOT NULL,
    price            DOUBLE PRECISION NOT NULL CHECK ( price > 0 ),
    rental_days      INTEGER          NOT NULL CHECK ( rental_days > 0 ),
    status           VARCHAR(10)      NOT NULL,
    state            VARCHAR(10)      NOT NULL,
    creator          VARCHAR(50)      NOT NULL,
    date_of_creation TIMESTAMP        NOT NULL
);

CREATE TABLE request
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(50) NOT NULL,
    phone            VARCHAR(30) NOT NULL UNIQUE,
    status           VARCHAR(10) NOT NULL,
    massage          VARCHAR(100),
    date_of_creation TIMESTAMP   NOT NULL
);


INSERT INTO users (full_name, email, phone, address, date_of_birthday, passwords, agreement, roles, date_of_creation)
values ('Ivan Ivanov', 'admin@mail.ru', '+375447876655', 'Gomel,Mazurova,20', '1986-05-02',
        '{bcrypt}$2a$10$2Il/sRkN70.1LHkL46rqju9tieea5lALI05c0UVVh2D4Xtar3Hoh2', true, 'ADMIN', '2023-05-25');

INSERT INTO users (full_name, email, phone,  address, date_of_birthday, passwords, agreement, roles, date_of_creation)
values ('Artem Dzuba', 'cards@mail.ru', '+375447876633',  'Gomel,Mazurova,20', '1986-05-04',
        '{bcrypt}$2a$10$2Il/sRkN70.1LHkL46rqju9tieea5lALI05c0UVVh2D4Xtar3Hoh2', true, 'USER', '2023-05-27');


INSERT INTO car
(image, color, type_car, state_check, quantity_doors, numbers, quantity_places, trunk_volume, vin_code, brand,
 engine_capacity,
 fuel_consumption, fuel, horse_power, transmission, model, status, price, year_of_release)
VALUES ('https://rent-auto.by/wp-content/uploads/2018/12/renault-logan.jpg', 'WHITE', 'COMFORT', 'READY', 5, '1092873',
        5, 587,
        '123-0948098j882d', 'Renault', 1.5, 7, 'DIESEL', 125, 'AUTOMATIC',
        'Logan', 'FREE', 102, 2020);

INSERT INTO car
(image, color, type_car, state_check, quantity_doors, numbers, quantity_places, trunk_volume, vin_code, brand,
 engine_capacity,
 fuel, fuel_consumption, horse_power, transmission, model, status, price, year_of_release)
VALUES ('https://rent-auto.by/wp-content/uploads/2018/11/kia-rio.jpg', 'BLACK', 'ECONOMIC', 'READY', 5, '1876786', 5,
        580,
        '123-0945656876',
        'Kia', 1.5, 'DIESEL', 7.4, 124, 'AUTOMATIC',
        'Rio', 'FREE', 102, 2020);


INSERT INTO rental (car_id, user_id, rental_date, return_date, price, rental_days, status, state, creator,
                    date_of_creation)
VALUES (1, 1, '2023-05-20', '2023-05-23', 100, 3, 'CHECK', 'ACTIVE', 'USER', '2023-05-20');

INSERT INTO documents(user_id, passport_No, driver_license_No, status_check)
VALUES (2, '1209838', 'PAO123986', 'CONFIRMED');

INSERT INTO request (username, phone, status, massage, date_of_creation)
VALUES ('Ivan', '+375447837465', 'OPEN', 'Could not get through', '2023-07-12')